Update profile page
portalsuperacao/superacao-app pull request #7
Opened 2017-04-04 16:43 UTC by diegodsgarcia

2017-04-05 01:47 UTC, abmxer commented
Na descrição do PR você pode descrever o que precisa ser testado?

2017-04-05 12:15 UTC, diegodsgarcia commented
Testar todos os componentes da tela de edição de perfil

2017-04-05 13:20 UTC, thompsonemerson commented
@diegodsgarcia nas próximas vezes adiciona uma descrição informando o que cê fez e tals para facilitar na hora de revisar.

2017-04-05 21:48 UTC, dpacosta reviewed
Comecei a dar uns feedbacks das nomenclaturas, mas acabei vendo que tem algumas variaveis q misturam ingles com portugues tambem. Talvez seja melhor a gente fazer uma revisao disso posteriormente.

2017-04-05 21:48 UTC, dpacosta commented on src/pages/profile/edit/edit.ts
> +        cancer_name: [this.user.cancer_name],
Acredito que _cancer_type_ aqui seria melhor. Quando tenho duvida de nomenclatura vou pelo que tem mais resultado nas buscas do google 😛

2017-04-05 21:48 UTC, dpacosta commented on src/pages/profile/edit/edit.ts
> +        cancer_name_past: [this.user.cancer_name_past],
past_cancer_type faz mais sentido no ingles

2017-04-05 21:48 UTC, dpacosta commented on src/pages/profile/edit/edit.ts
> +        type_participant: [this.user.type_participant],
participant_type

2017-04-05 21:48 UTC, dpacosta commented on src/pages/profile/edit/edit.ts
> +        metastase: [this.user.type_cancer ? this.user.type_cancer.metastase : null],
Por convencao, costuma-se usar prefixos em variaveis booleanas. Aqui seria is_metastase.
[Referencia](https://www.google.ca/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=boolean%20variable%20name%20convention&oq=boolean%20variable%20name%20convention&aqs=chrome.0.69i59j0l4j69i60.1887j0j7)

2017-04-05 21:48 UTC, dpacosta commented on src/pages/profile/edit/edit.ts
> +        reicidiva: [this.user.type_cancer ? this.user.type_cancer.reicidiva : null],
is_reicidiva ou is_recurrent

2017-04-05 22:13 UTC, rdiegoss reviewed
Só alguns pontos em relação a ortografia.

2017-04-05 22:13 UTC, rdiegoss commented on src/pages/profile/edit/edit.ts
> +      datas.treatment.terapia_naturais = formDatas.treatmentTerapiaNaturais;
"terapias_naturais"

2017-04-05 22:13 UTC, rdiegoss commented on src/pages/profile/profile.html
> +      <div class="title"> Nome do cancer </div>
Cancêr

2017-04-05 22:13 UTC, rdiegoss commented on src/pages/profile/profile.html
> +      <div class="title"> Tipo do cancer </div>
Câncer

2017-04-06 03:02 UTC, abmxer commented on src/pages/profile/profile.html
> +      <div class="title"> Nome do cancer </div>
Câncer ;-)

2017-04-06 13:30 UTC, thompsonemerson requested changes

2017-04-06 13:30 UTC, thompsonemerson commented on src/pages/profile/profile.ts
> +    return Number(value)
Alterar: 
`return Number(value)`
Por:
`return +value`

O `+` é mais performático que `Number()`

2017-04-06 20:39 UTC, diegodsgarcia commented on src/pages/profile/profile.ts
> +    return Number(value)
Nossa sério? Realmente não sabia disso... Você tem algum referencia, pra eu estudar mais sobre?

2017-04-06 20:39 UTC, merged